# [Info]
site_name: ã€Black Network Toolsã€‘  âœˆï¸@PUSHHHKKK # å·¦ä¸Šè§’æ ‡é¢˜
site_url: https://woodstw.github.io/
site_author: âœˆï¸@PUSHHHKKK 
site_description: âœˆï¸@PUSHHHKKK 

# [Navigtion]
Nav:
  - A â¤ï¸ Tool download ğŸ§°:
    - A â¤ï¸ Tool download ğŸ§°/index.md
    - A â¤ï¸ Tool download ğŸ§°/others/others.md
    - All:
      - A â¤ï¸ Tool download ğŸ§°/All/all.md   
    - PUSH:
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2301.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2302.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2303.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2304.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2305.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2306.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2307.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2308.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/2309.md
      - A â¤ï¸ Tool download ğŸ§°/PUSH/23010.md
    - K8tools:
      - A â¤ï¸ Tool download ğŸ§°/K8tools/o2301.md  
  - Document:
    - Document/index.md
    - Document/IM2301.md
    - Document/IM2302.md
    - Document/IM2303.md
    - Document/IM2304.md
    - Document/IM2305.md
    - Document/IM2306.md
    - Document/IM2307.md
    - Document/IM2308.md
    - Document/IM2309.md
    - Document/IM2310.md
    - Document/IM2312.md
    - Document/IM2313.md
    - Document/IM2314.md
    - Document/IM2315.md
    - Document/IM2316.md
    - Document/IM2317.md
    - Document/IM2318.md
    - Document/IM2319.md
    - Document/IM2320.md
    - Document/IM2321.md
    - Document/IM2322.md
    - Document/IM2323.md
    - Document/IM2324.md
    - Document/IM2325.md
    - Document/IM2326.md
    - Document/IM2327.md
  - Doc2:
    - Doc2/index.md
      Doc2/shell/PGT12301.md
      Doc2/shell/PGT12302.md
  - Doc3:
    - Doc3/index.md
    - Doc3/Z2301.md
    - Doc3/Z2302.md
    - Doc3/Z2303.md
    - Doc3/Z2304.md
    - Doc3/Z2305.md
    - Doc3/Z2306.md
  - Network tools:
    - Network tools/index.md
    - notes:
      - Network tools/notes/2307.md
      - Network tools/notes/2306.md
      - Network tools/notes/2305.md
      - Network tools/notes/2304.md
      - Network tools/notes/2303.md
      - Network tools/notes/2302.md
      - Network tools/notes/2301.md
      - Network tools/notes/2211-2212.md
      - Network tools/notes/2209-2210.md
      - Network tools/notes/2207-2208.md
      - Network tools/notes/2205-2206.md
      - Network tools/notes/2203-2204.md
      - Network tools/notes/2201-2202.md
      - Network tools/notes/2111-2112.md
      - Network tools/notes/2109-2110.md
      - Network tools/notes/2107-2108.md
      - Network tools/notes/2105-2106.md
      - Network tools/notes/2103-2104.md
      - Network tools/notes/2101-2102.md
      - Network tools/notes/2011-2012.md
      - Network tools/notes/2009-2010.md
      - Network tools/notes/2007-2008.md
      - Network tools/notes/2005-2006.md
      - Network tools/notes/2003-2004.md
      - Network tools/notes/2001-2002.md
      - Network tools/notes/0.md
      - Network tools/notes/1906-1912.md
      - Network tools/notes/1807-1812.md
      - Network tools/notes/1801-1806.md
      - Network tools/notes/17.md
      - Network tools/notes/16.md
      - Network tools/notes/230822.md
  - å…³äºPUSH:
    - ME/index.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # æ—¥é—´æ¨¡å¼
      primary: indigo # ä¸Šæ–¹çš„
      accent: orange # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/weather-night # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - scheme: slate # å¤œé—´æ¨¡å¼
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  features:
    - navigation.tabs # ä½¿ç”¨Tabæ¥è¿›è¡Œåˆ†ç±»
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.indexes # Tabä¼šæœ‰ä¸€ä¸ªindex.md è€Œä¸æ˜¯åœ¨æ‰“å¼€Tabæ—¶æ‰“å¼€ç¬¬ä¸€ç¯‡æ–‡ç« 
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - content.code.copy # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
    - content.action.edit # ç‚¹å‡»æŒ‰é’®è·³è½¬åˆ°ç¼–è¾‘é¡µé¢  éœ€è¦ç»“åˆ edit_uri ä¸€èµ·ä½¿ç”¨
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    repo: fontawesome/brands/telegram
edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
## [top-right corner]
repo_url: https://github.com/woodstw/woodstw.github.io # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: âœˆï¸@PUSHHHKKK # å³ä¸Šè§’çš„åå­—
## [bottom-left corner]
copyright: Push CC-BY-4.0 # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/telegram
      link: https://woodstw.github.io/pic/IMEAXXX.png
      name: Telegram | âœˆï¸@PUSHHHKKK # é¼ æ ‡æ‚¬æµ®æç¤º
    - icon: fontawesome/brands/github
      link: https://woodstw.github.io
      name: GitHub | âœˆï¸@PUSHHHKKK 

# [Extensions]
plugins:
  - search: # ç°åœ¨è¿˜ä¸æ”¯æŒä¸­æ–‡æœç´¢ æ”¯æŒä¹‹åå¯ä»¥è®¾ç½®è¯­è¨€
    # insiderå·²ç»æ”¯æŒä¸­æ–‡çš„åˆ†è¯æœç´¢äº† https://squidfunk.github.io/mkdocs-material/Word/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾ https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - attr_list # ç»™å›¾ç‰‡åé¢æ·»åŠ {width="300"}è®¾ç½®å¤§å°
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      # linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonitionéœ€è¦

extra_javascript:
  # latexæ”¯æŒ
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # ä¸ä½¿ç”¨åº•éƒ¨çš„ç¿»é¡µ
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  
  
